### ISSUE TITLE
Signup for individual matches

### ISSUE THREAD

**Issue by nohr-ai** [nohr-ai/CS-Team-Bot#45]
Problem
===

 Currently the match signup is for all matches on a given time, this is problematic with people who want to play but have to leave early, or in the last example when people have a kid and cannot play simultaneously.

Proposal
---
Allowing for a finer granularity of signups, we can handle potential problems and see if we need rescheduling sooner than we can now. I think people often make an extra effort to be present for the matches but would instead do something else.

- Solve this by having a per match team rotation, instead of per game-day.

Problems
---
What is the proper handling of matches with too few players? 
- Should the matchday be canceled
- Should random people from other matches be put in under a (maybe)
- Should it be an end-user problem and dealt with outside the bot, as we do now?

**Comment by EdvardPedersen** [comment]
My immediate thought is PEBCAK, and that this would add massive complications both for users and for the bot (bot: skill-based balancing between maps, balancing attendance to prioritize (or not?) people who can only attend a subset of maps, can no longer use the ban order mechanism (where we swap the order of teams based on the pick/ban) - users: remembering to sign up for all matches)

I vote no
